clc; clear all; close all;

img = imread('5.jpg');

if length(size(img))==3
    img = rgb2gray(img);
end

img_saltNoise = imnoise(img,'salt & pepper', 0.05);

imwrite(img_saltNoise,'5-nosy.jpg')

bitpage_img = listbitget(img);
bitpage_img_saltNoise = listbitget(img_saltNoise);


figure(1),
subplot(1,2,1), imshow(img), title('orginal img')
subplot(1,2,2), imshow(img_saltNoise), title('salt and pepper noise img')

figure(2)
subplot(2,4,1),imshow(bitpage_img(:,:,1)); title('bit0')
subplot(2,4,2);imshow(bitpage_img(:,:,2)); title('bit1')
subplot(2,4,3);imshow(bitpage_img(:,:,3)); title('bit2')
subplot(2,4,4);imshow(bitpage_img(:,:,4)); title('bit3')
subplot(2,4,5);imshow(bitpage_img(:,:,5)); title('bit4')
subplot(2,4,6);imshow(bitpage_img(:,:,6)); title('bit5')
subplot(2,4,7);imshow(bitpage_img(:,:,7)); title('bit6')
subplot(2,4,8);imshow(bitpage_img(:,:,8)); title('bit7')

%=======================================================
%=======================================================
figure(3)
subplot(2,4,1),imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)+bitpage_img_saltNoise(:,:,7))...
    +bitpage_img_saltNoise(:,:,6))+bitpage_img_saltNoise(:,:,5))+bitpage_img_saltNoise(:,:,4))...
    +bitpage_img_saltNoise(:,:,3))+bitpage_img_saltNoise(:,:,2))+bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img bit 0 to 7')

subplot(2,4,2);imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)+bitpage_img_saltNoise(:,:,7))...
    +bitpage_img_saltNoise(:,:,6))+bitpage_img_saltNoise(:,:,5))+bitpage_img_saltNoise(:,:,4))...
    +bitpage_img_saltNoise(:,:,3))+bitpage_img_saltNoise(:,:,2))...
    , []);
title('noised img bit 1 to 7')

subplot(2,4,3);imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)+bitpage_img_saltNoise(:,:,7))...
    +bitpage_img_saltNoise(:,:,6))+bitpage_img_saltNoise(:,:,5))+bitpage_img_saltNoise(:,:,4))...
    +bitpage_img_saltNoise(:,:,3)))...
    , []);
title('noised img bit 2 to 7')

subplot(2,4,4);imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)+bitpage_img_saltNoise(:,:,7))...
    +bitpage_img_saltNoise(:,:,6))+bitpage_img_saltNoise(:,:,5))+bitpage_img_saltNoise(:,:,4))))...
    , []);
title('noised img bit 3 to 7')

subplot(2,4,5);imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)+bitpage_img_saltNoise(:,:,7))...
    +bitpage_img_saltNoise(:,:,6))+bitpage_img_saltNoise(:,:,5)))))...
    , []);
title('noised img bit 4 to 7')

subplot(2,4,6);imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)+bitpage_img_saltNoise(:,:,7))...
    +bitpage_img_saltNoise(:,:,6))))))...
    , []);
title('noised img bit 5 to 7')

subplot(2,4,7);imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)+bitpage_img_saltNoise(:,:,7)))))))...
    , []);
title('orginal bit 6 to 7')

subplot(2,4,8);imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)))))))...
    , []);
title('noised img bit 7 to 7')

%=======================================================
%=======================================================
figure(4)
subplot(2,4,1),imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)+bitpage_img_saltNoise(:,:,7))...
    +bitpage_img_saltNoise(:,:,6))+bitpage_img_saltNoise(:,:,5))+bitpage_img_saltNoise(:,:,4))...
    +bitpage_img_saltNoise(:,:,3))+bitpage_img_saltNoise(:,:,2))+bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img bit 0 to 7')

subplot(2,4,2);imshow(...
    2*(2*(2*(2*(2*(2*(bitpage_img_saltNoise(:,:,7))...
    +bitpage_img_saltNoise(:,:,6))+bitpage_img_saltNoise(:,:,5))+bitpage_img_saltNoise(:,:,4))...
    +bitpage_img_saltNoise(:,:,3))+bitpage_img_saltNoise(:,:,2))+bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img bit 0 to 6')

subplot(2,4,3);imshow(...
    2*(2*(2*(2*(2*(...
    +bitpage_img_saltNoise(:,:,6))+bitpage_img_saltNoise(:,:,5))+bitpage_img_saltNoise(:,:,4))...
    +bitpage_img_saltNoise(:,:,3))+bitpage_img_saltNoise(:,:,2))+bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img bit 0 to 5')

subplot(2,4,4);imshow(...
    2*(2*(2*(2*(bitpage_img_saltNoise(:,:,5))+bitpage_img_saltNoise(:,:,4))...
    +bitpage_img_saltNoise(:,:,3))+bitpage_img_saltNoise(:,:,2))+bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img bit 0 to 4')

subplot(2,4,5);imshow(...
    2*(2*(2*(bitpage_img_saltNoise(:,:,4))...
    +bitpage_img_saltNoise(:,:,3))+bitpage_img_saltNoise(:,:,2))+bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img bit 0 to 3')

subplot(2,4,6);imshow(...
    2*(2*(...
    bitpage_img_saltNoise(:,:,3))+bitpage_img_saltNoise(:,:,2))+bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img bit 0 to 2')

subplot(2,4,7);imshow(...
    2*(...
    bitpage_img_saltNoise(:,:,2))+bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img bit 0 to 1')

subplot(2,4,8);imshow(...
    bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img bit 0 to 0')


%=============================================================
%=============================================================
figure(5)
subplot(1,3,1),imshow(img_saltNoise),title('noised img')
subplot(1,3,2),imshow(...
    2*(2*(2*(2*(2*(2*(2*bitpage_img_saltNoise(:,:,8)+bitpage_img_saltNoise(:,:,7))...
    +bitpage_img_saltNoise(:,:,6))+bitpage_img_saltNoise(:,:,5)))))...
    , []);
title('noised img bit 4 to 7')

subplot(1,3,3);imshow(...
    2*(2*(2*bitpage_img_saltNoise(:,:,4)+bitpage_img_saltNoise(:,:,3))...
    +bitpage_img_saltNoise(:,:,2))+bitpage_img_saltNoise(:,:,1)...
    , []);
title('noised img 0 to 3')


